### ISSUE TITLE
Incompatibility PHP8.1

### ISSUE THREAD

**Issue by qgt-mycelium** [giggsey/libphonenumber-for-php-lite#10]
#### Current behavior

- `PhoneNumberUtil::getInstance()` create a exception when it's use without ` PhoneNumberUtil::resetInstance();` before , the message exception is `"exception": "[object] (Error(code: 0): Typed static property libphonenumber\\PhoneNumberUtil::$instance must not be accessed before initialization at /var/task/vendor/giggsey/libphonenumber-for-php-lite/src/PhoneNumberUtil.php:387)
`

- When I use `PhoneNumberUtil::getInstance()` function, I have a other message like that : `PHP message: PHP Deprecated:  Optional parameter $defaultRegionMetadata declared before required parameter $phoneNumber is implicitly treated as a required parameter in /var/task/vendor/giggsey/libphonenumber-for-php-lite/src/PhoneNumberUtil.php on line 1795`

#### Excepted behavior

- `PhoneNumberUtil::getInstance()` must be use without `PhoneNumberUtil::resetInstance()` first time
- Parameter `$defaultRegionMetadata` should not be to have a default value

**Comment by giggsey** [comment]
getInstance() without resetInstance() was resolved in #9, just pending a new release.

I'll take a look at `$defaultRegionMetadata`, thanks

**Comment by qgt-mycelium** [comment]
Thanks
