### ISSUE TITLE
Valid mobile number für Germany (DE) does not work anymore

### ISSUE THREAD

**Issue by Enaah** [giggsey/libphonenumber-for-php-lite#77]
Hi @giggsey.

I have a package in use ([`propaganistas/laravel-phone`](https://github.com/Propaganistas/Laravel-Phone)) which uses this package ([`libphonenumber-for-php-lite`](https://github.com/giggsey/libphonenumber-for-php-lite)) as a dependency.   

In the `8.13.48` release you changed the metadata for DE (https://github.com/giggsey/libphonenumber-for-php-lite/releases/tag/8.13.48).  

Now a valid (mobile) number is no longer valid. 
Is is possible that there is a mistake in the new pattern? (old pattern `'15310\\d{6}|1(?:6[023]|7[0-57-9])\\d{7,8}|1(?:5[0-25-9]|76)\\d{8}'` - new pattern: `16[023]\\d{7,8}|1(?:5310|7[0-57-9]\\d)\\d{6}|1(?:5[0-25-9]|76)\\d{8}`).  

Lookup services like https://freetools.textmagic.com/phone-validator say the following number is valid, but you package says, it is not (anymore): `+4917259354218`  

![Bildschirmfoto 2024-11-11 um 22 15 46](https://github.com/user-attachments/assets/3570166b-4a14-4a44-92a4-e82952782ad7).

same with: https://messente.com/phone-validator  

![Bildschirmfoto 2024-11-11 um 22 17 21](https://github.com/user-attachments/assets/17f83bbf-45e4-4cd2-ad9d-34e78d6b9066)  

I can provide more (now) invalid numbers, if you want.  

Thanks for your work in OSS! :)

**Comment by giggsey** [comment]
Hi,

Please check the [FAQ](https://github.com/giggsey/libphonenumber-for-php#problems-with-invalid-numbers) for checking with invalid numbers.

You'll need to check the number using [Google's Demo](https://libphonenumber.appspot.com/), then report the issue to them if the number still shows as invalid.

**Comment by Enaah** [comment]
Sorry for missing these clear instructions 🤦🏼

Thanks!
